from pathlib import Path

TARGET_URL = "https://travel.state.gov/content/travel/en/legal/visa-law0/visa-statistics/nonimmigrant-visa-statistics/monthly-nonimmigrant-visa-issuances.html"  # Substitua pela URL do site
OUTPUT_FILE = Path("data/structured_excel_data.json")  # For the structured data
DOWNLOAD_DIR = Path("data/downloads")  # Directory to save downloaded Excel files

mapping_post_country = {
    "Afghanistan": {"location": "Kabul (E)", "visa_services": "Service currently suspended. For more information, click here"},
    "Albania": {"location": "Tirana (E)", "visa_services": "All"},
    "Algeria": {"location": "Algiers (E)", "visa_services": "All"},
    "Angola": {"location": "Luanda (E)", "visa_services": "All"},
    "Argentina": {"location": "Buenos Aires (E)", "visa_services": "All"},
    "Armenia": {"location": "Yerevan (E)", "visa_services": "All"},
    "Australia": [
        {"location": "Melbourne (CG)", "visa_services": "NIV"},
        {"location": "Sydney (CG)", "visa_services": "All"},
        {"location": "Perth (CG)", "visa_services": "NIV"},
    ],
    "Austria": {"location": "Vienna (E)", "visa_services": "All"},
    "Azerbaijan": {"location": "Baku (E)", "visa_services": "NIV"},
    "Bahamas": {"location": "Nassau (E)", "visa_services": "All"},
    "Bahrain": {"location": "Manama (CG)", "visa_services": "All"},
    "Bangladesh": {"location": "Dhaka (E)", "visa_services": "All"},
    "Barbados": {"location": "Bridgetown (E)", "visa_services": "All"},
    "Belarus": {
        "location": "Minsk (E)",
        "visa_services": "Services currently suspended. For more information, click here.",
    },
    "Belgium": {"location": "Brussels (E)", "visa_services": "All"},
    "Belize": {"location": "Belmopan (E)", "visa_services": "All"},
    "Benin": {"location": "Cotonou (E)", "visa_services": "All"},
    "Bermuda": {"location": "Hamilton (CG)", "visa_services": "All"},
    "Bolivia": {"location": "La Paz (E)", "visa_services": "All"},
    "Bosnia And Herzegovina": {"location": "Sarajevo (E)", "visa_services": "All"},
    "Botswana": {"location": "Gaborone (E)", "visa_services": "NIV"},
    "Brazil": [
        {"location": "Brasilia (E)", "visa_services": "NIV"},
        {"location": "Rio de Janeiro (CG)", "visa_services": "All"},
        {"location": "Sao Paulo (CG)", "visa_services": "NIV"},
        {"location": "Recife (C)", "visa_services": "NIV"},
    ],
    "Brunei": {"location": "Bandar Seri Begawan (E)", "visa_services": "NIV"},
    "Bulgaria": {"location": "Sofia (E)", "visa_services": "All"},
    "Burkina Faso": {"location": "Ouagadougou (E)", "visa_services": "All"},
    "Burma": {"location": "Rangoon (E)", "visa_services": "All"},
    "Burundi": {"location": "Bujumbura (E)", "visa_services": "NIV"},
    "Cambodia": {"location": "Phnom Penh (E)", "visa_services": "All"},
    "Cameroon": {"location": "Yaounde (E)", "visa_services": "All"},
    "Canada": [
        {"location": "Ottawa (E)", "visa_services": "NIV"},
        {"location": "Calgary (CG)", "visa_services": "NIV"},
        {"location": "Halifax (CG)", "visa_services": "NIV"},
        {"location": "Montreal (CG)", "visa_services": "All"},
        {"location": "Quebec (CG)", "visa_services": "NIV"},
        {"location": "Toronto (CG)", "visa_services": "NIV"},
        {"location": "Vancouver (CG)", "visa_services": "NIV & K"},
    ],
    "Cabo Verde": {"location": "Praia (E)", "visa_services": "All"},
    "Central African Republic": {"location": "Closed (E)", "visa_services": "None"},
    "Chad": {"location": "N'Djamena (E)", "visa_services": "NIV"},
    "Chile": {"location": "Santiago (E)", "visa_services": "All"},
    "China": [
        {"location": "Beijing (E)", "visa_services": "NIV"},
        {"location": "Guangzhou (CG)", "visa_services": "All"},
        {"location": "Shanghai (CG)", "visa_services": "NIV"},
        {"location": "Shenyang (CG)", "visa_services": "NIV"},
    ],
    "Colombia": {"location": "Bogota (E)", "visa_services": "All"},
    "Congo, Democratic Republic Of The": {
        "location": "Kinshasa (E)",
        "visa_services": "All",
    },
    "Congo, Republic Of The": {"location": "Brazzaville (E)", "visa_services": "All"},
    "Costa Rica": {"location": "San Jose (E)", "visa_services": "All"},
    "Cote D'ivoire": {"location": "Abidjan (E)", "visa_services": "All"},
    "Croatia": {"location": "Zagreb (E)", "visa_services": "NIV"},
    "Cuba": {
        "location": "Havana (E)",
        "visa_services": "IV and limited NIV. For more information, click here.",
    },
    "Cyprus": {"location": "Nicosia (E)", "visa_services": "NIV"},
    "Czech Republic": {"location": "Prague (E)", "visa_services": "All"},
    "Denmark": {"location": "Copenhagen (E)", "visa_services": "NIV"},
    "Djibouti": {"location": "Djibouti (E)", "visa_services": "All"},
    "Dominican Republic": {"location": "Santo Domingo (E)", "visa_services": "All"},
    "Ecuador": [
        {"location": "Quito (E)", "visa_services": "NIV"},
        {"location": "Guayaquil (CG)", "visa_services": "All"},
    ],
    "Egypt": {"location": "Cairo (E)", "visa_services": "All"},
    "El Salvador": {"location": "San Salvador (E)", "visa_services": "All"},
    "Estonia": {"location": "Tallinn (E)", "visa_services": "All"},
    "Equatorial Guinea": {"location": "Malabo (E)", "visa_services": "NIV"},
    "Eritrea": {"location": "Asmara (E)", "visa_services": "NIV"},
    "Ethiopia": {"location": "Addis Ababa (E)", "visa_services": "All"},
    "Fiji": {"location": "Suva (E)", "visa_services": "All"},
    "Finland": {"location": "Helsinki (E)", "visa_services": "All"},
    "France": {"location": "Paris (E)", "visa_services": "All"},
    "Gabon": {"location": "Libreville (E)", "visa_services": "All"},
    "Gambia, The": {"location": "Banjul (E)", "visa_services": "NIV"},
    "Georgia": {"location": "Tbilisi (E)", "visa_services": "All"},
    "Germany": [
        {"location": "Berlin (E)", "visa_services": "NIV"},
        {"location": "Frankfurt (CG)", "visa_services": "All"},
        {"location": "Munich (CG)", "visa_services": "NIV"},
    ],
    "Ghana": {"location": "Accra (E)", "visa_services": "All"},
    "Greece": {"location": "Athens (E)", "visa_services": "All"},
    "Guatemala": {"location": "Guatemala City (E)", "visa_services": "All"},
    "Guinea": {"location": "Conakry (E)", "visa_services": "NIV"},
    "Guyana": {"location": "Georgetown (E)", "visa_services": "All"},
    "Haiti": {
        "location": "Port-Au-Prince (E)",
        "visa_services": "Routine Services suspended",
    },
    "Honduras": {"location": "Tegucigalpa (E)", "visa_services": "All"},
}